# Generated by Django 5.0.7 on 2024-08-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_full_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
    ]
