# Generated by Django 5.0.7 on 2024-08-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_rename_original_bag_order_original_cart'),
        ('user_profile', '0003_userprofile_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_profile.userprofile'),
        ),
    ]
