# Generated by Django 5.0.7 on 2024-08-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_stripe_pid'),
        ('user_profile', '0005_rename_full_name_shippingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.shippingaddress'),
        ),
    ]
