# Generated by Django 5.0.7 on 2024-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
