# Generated by Django 5.0.7 on 2024-08-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_rename_full_name_shippingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='delivery_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='delivery_name',
            new_name='delivery_first_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='first_name',
            new_name='delivery_last_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='delivery_phone_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='last_name',
        ),
    ]
