# Generated by Django 5.0.7 on 2024-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_email_shippingaddress_delivery_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_is_default',
            field=models.BooleanField(default=False),
        ),
    ]
