# Generated by Django 5.0.7 on 2024-08-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
