# Generated by Django 5.0.7 on 2024-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_status',
            field=models.IntegerField(choices=[(1, 'not available'), (2, 'available'), (3, 'pre-order')], default=1, help_text='Preorder status based on stock availability.'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock must be a non-negative integer.'),
        ),
    ]
